kind: PersistentVolume
apiVersion: v1
metadata:
  name: cesae-contacts-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/cesae-contacts-db"
